/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AngsuranController;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Fitriany Chairunnisa
 */
public class AngsuranJInternalFrame extends javax.swing.JInternalFrame {
    private String header[] = {"No. Transaksi", "No. Identitas","Nama",
        "ID Gadai", "Tanggal Angsuran", "Jumlah Angsuran", "Denda"};
    private String[] headerTable={"id_angsuran","no_identitas","no_identitas",
            "id_gadai","tanggal_angsuran","jumlah_angsuran","denda"};
    /**
     * Creates new form AngsuranJInternalFrame
     */
    public AngsuranController ang;
    
    public AngsuranJInternalFrame() {
        initComponents();
        ang = new AngsuranController();
        ang.bindingAll(tblAngsuran, header);
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCariAng = new javax.swing.JComboBox<>();
        tfCariAngsur = new javax.swing.JTextField();
        btnCariAngsur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngsuran = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfIdAngsuran = new javax.swing.JTextField();
        tfNoIdentitasAng = new javax.swing.JTextField();
        tfIdGadaii = new javax.swing.JTextField();
        tfJmlAngsuran = new javax.swing.JTextField();
        tfDenda = new javax.swing.JTextField();
        btnSimpanAngsuran = new javax.swing.JButton();
        btnHapusAngsuran = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jDateAngsuran = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Angsuran");

        cmbCariAng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - Pilih - -", "No. Identitas", "ID Gadai", "No. Transaksi" }));

        btnCariAngsur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegadaian/Button-Next-icon.png"))); // NOI18N
        btnCariAngsur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariAngsurActionPerformed(evt);
            }
        });

        tblAngsuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAngsuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAngsuranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAngsuran);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("No. Transaksi");

        jLabel2.setText("No. Identitas");

        jLabel3.setText("ID Gadai");

        jLabel4.setText("Tanggal Angsuran");

        jLabel5.setText("Jumlah Angsuran");

        jLabel6.setText("Denda");

        tfIdAngsuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIdAngsuranKeyPressed(evt);
            }
        });

        btnSimpanAngsuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegadaian/Button-Ok-icon.png"))); // NOI18N
        btnSimpanAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanAngsuranActionPerformed(evt);
            }
        });

        btnHapusAngsuran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegadaian/Button-Delete-icon.png"))); // NOI18N
        btnHapusAngsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusAngsuranActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Form Angsuran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNoIdentitasAng, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJmlAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateAngsuran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(tfIdGadaii, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(btnSimpanAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnHapusAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapusAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpanAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tfIdAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfNoIdentitasAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(tfIdGadaii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4))
                            .addComponent(jDateAngsuran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfJmlAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35))))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pegadaian/pegadaian-header3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(cmbCariAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCariAngsur, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariAngsur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCariAng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCariAngsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnCariAngsur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusAngsuranActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin dihapus?");
        if (i == 0) {
            try {
                String pesan = "Gagal hapus";
                boolean hasil = ang.delete(tfIdAngsuran.getText());
                if (hasil) {
                    pesan = "Hore Berhasil";
                    //reset();
                }
                JOptionPane.showMessageDialog(this, pesan);
                ang.bindingAll(tblAngsuran, header);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        reset();
    }//GEN-LAST:event_btnHapusAngsuranActionPerformed

    private void btnCariAngsurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAngsurActionPerformed
        String kolom ="";
       switch (cmbCariAng.getSelectedIndex()){
           case 0:kolom="";break;
           case 1:kolom="no_identitas";break;
           case 2:kolom="id_gadai";break;
           case 3:kolom="id_angsuran";break;
       }
        
        ang.bindingSearch(tblAngsuran, header, kolom, tfCariAngsur.getText());
    }//GEN-LAST:event_btnCariAngsurActionPerformed

    private void btnSimpanAngsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanAngsuranActionPerformed
        boolean hasil = false;
        hasil = ang.save (tfIdAngsuran.getText(),tfNoIdentitasAng.getText(),tfIdGadaii.getText(),
                jDateAngsuran.getDate().getTime()+ "",
               tfJmlAngsuran.getText(),tfDenda.getText(),
               tfIdAngsuran.isEnabled());
        String pesan = "Gagal menambahkan data";
        if (hasil) {
            try {
                pesan = "Berhasil menambahkan Data";
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        JOptionPane.showMessageDialog(this, pesan);
        ang.bindingAll(tblAngsuran, header);
        reset();
    }//GEN-LAST:event_btnSimpanAngsuranActionPerformed

    private void tblAngsuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAngsuranMouseClicked
        tfIdAngsuran.setText("" + tblAngsuran.getValueAt(tblAngsuran.getSelectedRow(), 0) + "");
        tfNoIdentitasAng.setText("" + tblAngsuran.getValueAt(tblAngsuran.getSelectedRow(), 1) + "");
        tfIdGadaii.setText("" + tblAngsuran.getValueAt(tblAngsuran.getSelectedRow(), 3) + "");
        jDateAngsuran.setDate((Date) tblAngsuran.getValueAt(tblAngsuran.getSelectedRow(), 4));
        tfJmlAngsuran.setText("" + tblAngsuran.getValueAt(tblAngsuran.getSelectedRow(), 5) + "");
        tfDenda.setText("" + tblAngsuran.getValueAt(tblAngsuran.getSelectedRow(), 6) + "");
        
        tfIdAngsuran.setEnabled(false);
        tfNoIdentitasAng.setEnabled(false);
        tfIdGadaii.setEnabled(false);
        btnHapusAngsuran.setEnabled(true);
        btnSimpanAngsuran.setEnabled(true);
    }//GEN-LAST:event_tblAngsuranMouseClicked

    private void tfIdAngsuranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdAngsuranKeyPressed
        btnHapusAngsuran.setEnabled(true);
        btnSimpanAngsuran.setEnabled(true);
    }//GEN-LAST:event_tfIdAngsuranKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariAngsur;
    private javax.swing.JButton btnHapusAngsuran;
    private javax.swing.JButton btnSimpanAngsuran;
    private javax.swing.JComboBox<String> cmbCariAng;
    private com.toedter.calendar.JDateChooser jDateAngsuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAngsuran;
    private javax.swing.JTextField tfCariAngsur;
    private javax.swing.JTextField tfDenda;
    private javax.swing.JTextField tfIdAngsuran;
    private javax.swing.JTextField tfIdGadaii;
    private javax.swing.JTextField tfJmlAngsuran;
    private javax.swing.JTextField tfNoIdentitasAng;
    // End of variables declaration//GEN-END:variables
    public void reset(){
        tfIdAngsuran.setText("");
        tfNoIdentitasAng.setText("");
        tfCariAngsur.setText("");
        tfDenda.setText("");
        tfIdGadaii.setText("");
        tfJmlAngsuran.setText("");
        jDateAngsuran.setDate(new Date());
        btnSimpanAngsuran.setEnabled(false);
        btnHapusAngsuran.setEnabled(false); 
        tfIdAngsuran.setEnabled(true);
    }

}
