/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Jenis_BarangController;
import javax.swing.JOptionPane;

/**
 *
 * @author Fitriany Chairunnisa
 */
public class JenisJInternalFrame extends javax.swing.JInternalFrame {
    private String[] header={
            "ID Jenis Barang","Jenis Barang"};
    private String[] headerTable={"","id_jenis",
            "nama_jenis"};
    public Jenis_BarangController jb;
    /**
     * Creates new form JenisJInternalFrame
     */
    public JenisJInternalFrame() {
        initComponents();
        jb = new Jenis_BarangController();
        jb.bindingAll(tblJns, header);
        
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJns = new javax.swing.JTable();
        cmbJns = new javax.swing.JComboBox<>();
        cariJns = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIdJnsBarang = new javax.swing.JTextField();
        tfJnsBarang = new javax.swing.JTextField();
        btnSimpanJnsBarang = new javax.swing.JButton();
        btnHapusJnsBarang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfJnsBrg = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Jenis Barang");

        tblJns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJnsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJns);

        cmbJns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - Pilih - -", "ID", "Jenis" }));

        cariJns.setText("Cari");
        cariJns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariJnsActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("ID Jenis Barang");

        jLabel3.setText("Jenis Barang");

        tfIdJnsBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIdJnsBarangKeyPressed(evt);
            }
        });

        btnSimpanJnsBarang.setText("Simpan");
        btnSimpanJnsBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanJnsBarangActionPerformed(evt);
            }
        });

        btnHapusJnsBarang.setText("Hapus");
        btnHapusJnsBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusJnsBarangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form Jenis Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpanJnsBarang)
                .addGap(49, 49, 49)
                .addComponent(btnHapusJnsBarang)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIdJnsBarang)
                            .addComponent(tfJnsBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdJnsBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfJnsBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanJnsBarang)
                    .addComponent(btnHapusJnsBarang))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tfJnsBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJnsBrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cmbJns, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfJnsBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cariJns)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariJns)
                    .addComponent(tfJnsBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariJnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariJnsActionPerformed
//        String kolom ="";
//       switch (cmbJns.getSelectedIndex()){
//           case 0:kolom="";break;
//           case 1:kolom="id_jenis";break;
//           case 2:kolom="nama_jenis";break;
//       }

        jb.bindingSearch(tblJns, header, headerTable[cmbJns.getSelectedIndex()], tfJnsBrg.getText());
        
    }//GEN-LAST:event_cariJnsActionPerformed

    private void tfJnsBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJnsBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJnsBrgActionPerformed

    private void btnSimpanJnsBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanJnsBarangActionPerformed
        boolean hasil = false;
        
        if(!tfIdJnsBarang.isEnabled()){
         hasil=jb.update((Short.parseShort(tfIdJnsBarang.getText())),
         tfJnsBarang.getText());          
     }
        else{
        hasil=jb.update((Short.parseShort(tfIdJnsBarang.getText())),
         tfJnsBarang.getText());
        }
        
        tfIdJnsBarang.setEnabled(true);
        btnSimpanJnsBarang.setEnabled(true);
        String pesan = "Gagal menyimpan data";
        if (hasil) {
            pesan = "Berhasil menyimpan data";
        }
        JOptionPane.showMessageDialog(this, pesan);
        jb.bindingAll(tblJns, header);
        reset();
    }//GEN-LAST:event_btnSimpanJnsBarangActionPerformed

    private void tblJnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJnsMouseClicked
        tfIdJnsBarang.setText(tblJns.getValueAt(tblJns.getSelectedRow(), 0) + "");
        tfJnsBarang.setText(tblJns.getValueAt(tblJns.getSelectedRow(), 1) + "");

        tfIdJnsBarang.setEnabled(false);
        btnHapusJnsBarang.setEnabled(true);
        btnSimpanJnsBarang.setEnabled(true);
    }//GEN-LAST:event_tblJnsMouseClicked

    private void btnHapusJnsBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusJnsBarangActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Apakah Mau di hapus?");
        if (i == 0) {
            String pesan = "Gagal Hapus";
            boolean hasil = jb.delete(Short.parseShort(tfIdJnsBarang.getText()));
            if (hasil) {
                pesan = "Berhasil hapus";
            }
            JOptionPane.showMessageDialog(this, pesan);

            jb.bindingAll(tblJns, header);
            //reset();
            btnSimpanJnsBarang.setEnabled(true);
            btnHapusJnsBarang.setEnabled(true);
        }
    }//GEN-LAST:event_btnHapusJnsBarangActionPerformed

    private void tfIdJnsBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdJnsBarangKeyPressed
        btnHapusJnsBarang.setEnabled(true);
        btnSimpanJnsBarang.setEnabled(true);
    }//GEN-LAST:event_tfIdJnsBarangKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusJnsBarang;
    private javax.swing.JButton btnSimpanJnsBarang;
    private javax.swing.JButton cariJns;
    private javax.swing.JComboBox<String> cmbJns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJns;
    private javax.swing.JTextField tfIdJnsBarang;
    private javax.swing.JTextField tfJnsBarang;
    private javax.swing.JTextField tfJnsBrg;
    // End of variables declaration//GEN-END:variables

    public void reset() {
    tfIdJnsBarang.setText("");
    tfJnsBarang.setText("");
    cmbJns.setSelectedIndex(1);
    tfJnsBrg.setText("");
    btnSimpanJnsBarang.setEnabled(false);
    btnHapusJnsBarang.setEnabled(false);
}
}
